### ISSUE TITLE
support nanodet-plus to onnx ?

### ISSUE THREAD

**Issue by jcyhcs** [Kazuhito00/NanoDet-ONNX-Sample#1]
hi,professor:
refer to author's github:https://github.com/RangiLyu/nanodet, it update to nanodet-plus, so , can use your python script to convert the pth pretrained model to onnx format? 
please help !

**Comment by Kazuhito00** [comment]
ONNX export can be done with the following command as shown in the official repository.

```
python export_onnx.py \
    --cfg_path=config/nanodet-plus-m_320.yml \
    --model_path=nanodet-plus-m_320_checkpoint.ckpt \
    --out_path=nanodet-plus-m_320.onnx
```

However, the output shape is different from the legacy model, so the inference program needs to be modified.

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.
